## defaults
in_channels: 3
out_channels: 8

edge_dim: 4
concat: false

## ranges
hidden_channels: !!python/tuple
- 32
- 256

num_layers: !!python/tuple
- 3
- 8

lr: !!python/tuple
- 1.0e-05
- 0.001

dropout: !!python/tuple
- 0.0
- 0.5

depth: !!python/tuple
- 3
- 6

pool_ratios: !!python/tuple
- 0.5
- 0.9

heads: !!python/tuple
- 1
- 8

jk:
- last
- cat
- max
- null