## defaults
in_channels: 3
out_channels: 8
# edge_dim: 3
concat: false
hidden_channels: 250
num_layers: 6

## ranges
# hidden_channels:
# - 32
# - 64
# - 128
# - 256

# num_layers: !!python/tuple
# - 2
# - 20

lr: !!python/tuple
- 1.0e-05
- 0.001

dropout:
- 0.0
- 0.1
- 0.2
- 0.3
- 0.4
- 0.5

depth: !!python/tuple
- 3
- 6

pool_ratios: !!python/tuple
- 0.5
- 0.9

heads: !!python/tuple
- 1
- 5

K: !!python/tuple
- 1
- 4

add_self_loops:
- true
- false