TransformerConv:
  obj: !!python/name:torch_geometric.nn.conv.transformer_conv.TransformerConv ''
  params:
    edge_dim: basic
    heads: basic
    concat: basic
    beta:
    - true
    - false

PDNConv:
  obj: !!python/name:torch_geometric.nn.conv.pdn_conv.PDNConv ''
  params:
    edge_dim: basic
    ## also has hidden_channels but for edge features. this will use the same
    hidden_channels: basic