RGATConv:
  obj: !!python/name:torch_geometric.nn.conv.rgat_conv.RGATConv ''
  params:
    concat: basic
    dropout: basic
    heads: basic
    num_relations: !!python/tuple
    - 1
    - 5
    num_bases: !!python/tuple
    - 1
    - 3
    num_blocks: !!python/tuple
    - 1
    - 3
    mod:
    - additive
    - scaled
    - f-additive
    - f-scaled
    - null
    attention_mechanism:
    - within-relation
    - across-relation
    attention_mode:
    - additive-self-attention
    - multiplicative-self-attention
    dim: !!python/tuple
    - 1
    - 10


