AdaptiveWingLoss:
  obj: !!python/name:automesh.loss.AdaptiveWingLoss ''
  params:
    omega: !!python/tuple
    - 8.0
    - 30.0
    theta: !!python/tuple
    - 0.2
    - 0.8
    epsilon: !!python/tuple
    - 1.0
    - 2.0
    alpha: !!python/tuple
    - 2.1
    - 3.0

FocalLoss:
  obj: !!python/name:automesh.loss.FocalLoss ''
  params:
    alpha_f: !!python/tuple
    - 0.6
    - 1.0
    gamma_f: !!python/tuple
    - 0.0
    - 5.0

FocalTverskyLoss:
  obj: !!python/name:automesh.loss.FocalTverskyLoss ''
  params:
    gamma_ft: !!python/tuple
    - 1.0
    - 3.0

# BCEDiceLoss:
#   obj: !!python/name:automesh.loss.BCEDiceLoss ''

# DiceLoss:
#   obj: !!python/name:automesh.loss.DiceLoss ''

# JaccardLoss:
#   obj: !!python/name:automesh.loss.JaccardLoss ''

# TverskyLoss:
#   obj: !!python/name:automesh.loss.TverskyLoss ''
#   params:
#     alpha_t: !!python/tuple
#     - 0.0
#     - 1.0
